development:
  sessions:
    default:
      database: api_event_listener_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: api_event_listener_test
      hosts:
        - localhost:27017
  options:
      raise_not_found_error: false
